// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuabmREPVB5gInCtqgwmqU8nVA-7DRNm8',
    appId: '1:317018312053:web:524fb9c7499ed2ab16973c',
    messagingSenderId: '317018312053',
    projectId: 'chat-app-69bbe',
    authDomain: 'chat-app-69bbe.firebaseapp.com',
    databaseURL: 'https://chat-app-69bbe-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-69bbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCto1PnfQf_31NB9irlEnDjxkqNma-iBPM',
    appId: '1:317018312053:android:2c5eedc4f03f345616973c',
    messagingSenderId: '317018312053',
    projectId: 'chat-app-69bbe',
    databaseURL: 'https://chat-app-69bbe-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-69bbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYSdR7zCPSM9SUis55lCaXXPsd523OTDA',
    appId: '1:317018312053:ios:1ec18c4fd4409ed616973c',
    messagingSenderId: '317018312053',
    projectId: 'chat-app-69bbe',
    databaseURL: 'https://chat-app-69bbe-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-69bbe.appspot.com',
    iosBundleId: 'com.example.firstTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYSdR7zCPSM9SUis55lCaXXPsd523OTDA',
    appId: '1:317018312053:ios:047039c2c91c696816973c',
    messagingSenderId: '317018312053',
    projectId: 'chat-app-69bbe',
    databaseURL: 'https://chat-app-69bbe-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-69bbe.appspot.com',
    iosBundleId: 'com.example.firstTest.RunnerTests',
  );
}
